"""freelancer1

Revision ID: 3b2e5233f603
Revises: 5ecec719609e
Create Date: 2023-10-06 12:44:55.153684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2e5233f603'
down_revision: Union[str, None] = '5ecec719609e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'base', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'base', type_='unique')
    # ### end Alembic commands ###
