"""freelancer1

Revision ID: 5ecec719609e
Revises: 
Create Date: 2023-10-06 12:42:51.480239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ecec719609e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('client', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('descr', sa.String(), nullable=True),
    sa.Column('implementer', sa.Boolean(), nullable=True),
    sa.Column('listOfOrders', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('pendingTasks', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('activeBalance', sa.Integer(), nullable=True),
    sa.Column('frozenBalance', sa.Integer(), nullable=True),
    sa.Column('transactions', sa.String(), nullable=True),
    sa.Column('activeTasks', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('userStatus', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('descr', sa.String(), nullable=True),
    sa.Column('client', sa.Boolean(), nullable=True),
    sa.Column('implementer', sa.Boolean(), nullable=True),
    sa.Column('listOfOrders', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('listOfServices', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('timing', sa.String(), nullable=True),
    sa.Column('ownerId', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('descr', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('base')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
